# Generated by Django 5.0.6 on 2024-09-02 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtualizarHorimetro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horimetro', models.IntegerField(default='', verbose_name='Horimetro atualizado')),
            ],
        ),
        migrations.CreateModel(
            name='ModeloMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Modelo de Máquina')),
            ],
        ),
        migrations.CreateModel(
            name='Patrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frota', models.IntegerField(verbose_name='Número de frota')),
                ('horimetro', models.IntegerField(verbose_name='Horimetro de máquina')),
            ],
        ),
        migrations.CreateModel(
            name='Pecas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='AdicionarMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frota', models.IntegerField(default=0, verbose_name='Número de frota')),
                ('hora1', models.IntegerField(blank=True, null=True, verbose_name='Horas para preventiva 1')),
                ('hora2', models.IntegerField(blank=True, null=True, verbose_name='Horas para preventiva 2')),
                ('hora3', models.IntegerField(blank=True, null=True, verbose_name='Horas para preventiva 3')),
                ('hora4', models.IntegerField(blank=True, null=True, verbose_name='Horas para preventiva 4')),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maquinas.modelomaquina', verbose_name='Modelo de Máquina')),
            ],
        ),
        migrations.CreateModel(
            name='UltimaPreventiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frota', models.IntegerField(default=0, verbose_name='Número de frota')),
                ('horimetro', models.IntegerField(default=0, verbose_name='Horimetro de máquina')),
                ('modelo', models.CharField(default='', max_length=100, verbose_name='Modelo de máquina')),
                ('HoradePreventiva', models.IntegerField(default=0, verbose_name='Preventiva de quantas horas')),
                ('OS', models.IntegerField(default=0, verbose_name='Ordem de serviço')),
                ('pecas', models.ManyToManyField(to='maquinas.pecas', verbose_name='Peças usadas')),
            ],
        ),
    ]
