# Generated by Django 5.0.6 on 2024-09-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0003_alter_adicionarmaquina_horimetro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adicionarmaquina',
            name='horimetro',
        ),
        migrations.AlterField(
            model_name='atualizarhorimetro',
            name='horimetro',
            field=models.IntegerField(default=0, verbose_name='Horimetro atualizado'),
        ),
    ]
