# Generated by Django 5.0.6 on 2024-09-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0004_remove_adicionarmaquina_horimetro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ultimapreventiva',
            name='frota',
            field=models.IntegerField(default=0, verbose_name='Número de frota'),
        ),
    ]
