# Generated by Django 5.0.6 on 2024-09-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0005_alter_ultimapreventiva_frota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ultimapreventiva',
            name='horimetro',
            field=models.IntegerField(default=0, verbose_name='Horimetro de máquina'),
        ),
    ]
