# Generated by Django 5.0.6 on 2024-09-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0006_alter_ultimapreventiva_horimetro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ultimapreventiva',
            name='modelo',
            field=models.CharField(default=0, max_length=100, verbose_name='Modelo de máquina'),
        ),
    ]
