# Generated by Django 5.0.6 on 2024-09-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0008_alter_ultimapreventiva_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atualizarhorimetro',
            name='horimetro',
            field=models.IntegerField(blank=True, null=True, verbose_name='Horimetro atualizado'),
        ),
    ]
