# Generated by Django 5.0.6 on 2024-09-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0009_alter_atualizarhorimetro_horimetro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrimonio',
            name='horimetro',
            field=models.IntegerField(default=0, verbose_name='Horimetro de máquina'),
        ),
    ]
