# Generated by Django 5.0.6 on 2024-09-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0010_alter_patrimonio_horimetro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atualizarhorimetro',
            name='horimetro',
            field=models.IntegerField(default=0, verbose_name='Horimetro atualizado'),
        ),
        migrations.AlterField(
            model_name='ultimapreventiva',
            name='OS',
            field=models.IntegerField(default=0, verbose_name='Ordem de serviço'),
        ),
    ]
