# Generated by Django 5.0.6 on 2024-09-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0011_alter_atualizarhorimetro_horimetro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ultimapreventiva',
            name='HoradePreventiva',
            field=models.IntegerField(default='', verbose_name='Preventiva de quantas horas'),
        ),
    ]
