# Generated by Django 5.0.6 on 2024-09-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0012_alter_ultimapreventiva_horadepreventiva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ultimapreventiva',
            name='HoradePreventiva',
            field=models.IntegerField(default=0, verbose_name='Preventiva de quantas horas'),
        ),
    ]
