# Generated by Django 5.0.6 on 2024-09-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0014_adicionarmaquina_horimetro'),
    ]

    operations = [
        migrations.AddField(
            model_name='adicionarmaquina',
            name='Primeira',
            field=models.IntegerField(default=0, verbose_name='Horimetro da primerira preventiva'),
        ),
        migrations.AddField(
            model_name='adicionarmaquina',
            name='Segunda',
            field=models.IntegerField(default=0, verbose_name='Horimetro da segunda preventiva'),
        ),
        migrations.AddField(
            model_name='adicionarmaquina',
            name='Terceira',
            field=models.IntegerField(default=0, verbose_name='Horimetro da terceira preventiva'),
        ),
    ]
