# Generated by Django 5.0.6 on 2024-10-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0015_adicionarmaquina_primeira_adicionarmaquina_segunda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ultimapreventiva',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Data da ultima preventiva'),
        ),
    ]
