# Generated by Django 5.0.7 on 2024-11-14 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0016_ultimapreventiva_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adicionarmaquina',
            name='Terceira',
        ),
        migrations.RemoveField(
            model_name='adicionarmaquina',
            name='hora3',
        ),
        migrations.RemoveField(
            model_name='adicionarmaquina',
            name='hora4',
        ),
    ]
