# Generated by Django 5.0.7 on 2024-11-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0017_remove_adicionarmaquina_terceira_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adicionarmaquina',
            name='Terceira',
            field=models.IntegerField(default=0, verbose_name='Horimetro da terceira preventiva'),
        ),
        migrations.AddField(
            model_name='adicionarmaquina',
            name='hora3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Horas para preventiva 3'),
        ),
        migrations.AddField(
            model_name='adicionarmaquina',
            name='hora4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Horas para preventiva 4'),
        ),
    ]
