# Generated by Django 5.0.7 on 2024-11-16 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0018_adicionarmaquina_terceira_adicionarmaquina_hora3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('Administrador', 'Administrador'), ('Mecanico', 'Mecanico')], default='Mecanico', max_length=50, verbose_name='Tipo de Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='adicionarUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usuario', models.CharField(max_length=150, unique=True, verbose_name='Nome de Usuário')),
                ('senha', models.CharField(max_length=255, verbose_name='Senha')),
                ('tipo_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maquinas.tipousuario', verbose_name='Tipo de Usuário')),
            ],
        ),
    ]
