# Generated by Django 5.0.7 on 2024-11-16 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0020_remove_adicionarusuario_senha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adicionarusuario',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='adicionarusuario',
            name='tipo_usuario',
        ),
        migrations.RemoveField(
            model_name='adicionarusuario',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='TipoUsuario',
        ),
        migrations.DeleteModel(
            name='adicionarUsuario',
        ),
    ]
